**Shiny Application to model the effect of horsepower, number of cylinders, and weight on the mpg**
================================================================================
*Ankit Gupta*  
*Thursday, 24 December 2015*

## Overview:

1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application.
2. Deploy the application on Rstudio's shiny server
3. Share the application link by pasting it into the text box below
4. Share your server.R and ui.R code on github

The application must include the following:  

1. Some form of input (widget: textbox, radio button, checkbox, ...)
2. Some operation on the ui input in sever.R
3. Some reactive output displayed as a result of server calculations
4. You must also include enough documentation so that a novice user could use your application.

The documentation should be at the Shiny website itself. Do not post to an external link.
The Shiny application in question is entirely up to you. However, if you're having trouble coming up with ideas, you could start from the simple prediction algorithm done in class and build a new algorithm on one of the R datasets packages. Please make the package simple for the end user, so that they don't need a lot of your prerequisite knowledge to evaluate your application. You should emphasize a simple project given the short time frame.  

## Solution

The application applies linear model to the mtcars dataset, modeling the effect of horsepower, number of cylinders, and weight on the mpg.  Since the only valid possibilities for number of cylinders in the dataset were 4, 6, and 8, the choice are limited using radio buttons.  For the weight, reactive() is used to convert the user input weight into the units used by the model, lb/1000.  Finally, a pre-set function using the linear model is used to predict the mpg based on the three variables input by the user.

The Application is deployed using [Getting Started][1] .

[1]: http://shiny.rstudio.com/articles/shinyapps.html "Getting Started"